# Generated by Django 4.0.6 on 2022-11-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_programa_galeria_6'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel_7c',
            name='titulo_pestania',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
