# Generated by Django 4.0.6 on 2022-11-02 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_panel_7c_titulo_pestania'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel_7c',
            name='icono',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
